birthday1=input("First person enter your birthday")
birthday2=input("Second person enter your birthday")
birthday3=input("Third person enter your birthday")
birthday4=input("Fourth person enter your birthday")
birthday5=input("Fifth person enter your birthday")
print("The first person's birthday is on",birthday1)
print("The second person's birthday is on",birthday2)
print("The third person's birthday is on",birthday3)
print("The fourth person's birthday is on",birthday4)
print("The fifth person's birthday is on",birthday5)