import turtle
screen = turtle.Screen()
screen.bgcolor("lightblue")
screen.title("Python Coding Test - 1: Square")
t = turtle.Turtle()
t.forward(-80)
t.right(90)
t.forward(-80)
t.shape("turtle")
t.color("darkgreen", "yellow")
t.pensize(5)
t.speed(3)
t.begin_fill()
for _ in range(4):
    t.forward(160)
    t.left(90)
t.left(90)
t.forward(80)
t.right(90)
t.end_fill()
t.color("darkgreen","yellow")
t.forward(5)
t.color("yellow","yellow")
t.forward(72)
t.color("red","yellow")
screen.exitonclick()